### ISSUE TITLE
Loading a Project Page Throws Errors

### ISSUE THREAD

**Issue by jmwright** [stemn/stemn-frontend#4]
I just created a project on dev.stemn.com, and the readme takes a long time to load. The console shows these errors. My older projects seem to have the same problem.
```
Blocked loading mixed active content “http://itsasus.local:5555/fonts/glyphicons-halflings-regular.woff2”[Learn More] 5b15410c252c9400192ab940
Blocked loading mixed active content “http://itsasus.local:5555/fonts/fontawesome-webfont.woff2?v=4.7.0”[Learn More] 5b15410c252c9400192ab940
```
```
Error: Request failed with status code 524 vendor.7724a61f8b8e6788e05b.js:3:13778
```
That's with Firefox 60.0.1 (64-bit) on Ubuntu Linux 17.10

I do not seem to get the first two errors in Chrome 67.0.3396.62 (64-bit), but I still get the 524 error.
```
vendor.7724a61f8b8e6788e05b.js:3 Uncaught (in promise) Error: Request failed with status code 524
    at FtD3.e.exports (vendor.7724a61f8b8e6788e05b.js:3)
    at e.exports (vendor.7724a61f8b8e6788e05b.js:1)
    at XMLHttpRequest.p.(/anonymous function) (https://dev.stemn.com/js/vendor.7724a61f8b8e6788e05b.js:2:11560)
    at XMLHttpRequest.wrapped (raven.js:286)
```

**Comment by MrBlenny** [comment]
First 2 errors are probably related to a firefox extension. Last one is certainly a problem. @sabrehagen do you have access to more info in sentry? Looks like an API issue.

**Comment by MrBlenny** [comment]
Looks like this is fixed

**Comment by jmwright** [comment]
Thanks
